### ISSUE TITLE
Error during deployment: Dynamic require of "url" is not supported

### ISSUE THREAD

**Issue by cvyl** [jokester/socket.io-serverless#1]
I encountered an error when deploying using `wrangler` with the command `pnpm run --filter ./demo-server deploy:cf`. The error message is as follows:
```

> @jokester/sio-serverless-demo-server@0.0.1 deploy:cf /home/mikka/repos/socket.io-serverless/demo-server
> wrangler deploy


 ⛅️ wrangler 3.80.0 (update available 3.80.2)
---------------------------------------------

Total Upload: 670.65 KiB / gzip: 117.40 KiB
Your worker has access to the following bindings:
- Durable Objects:
  - engineActor: EngineActor
  - socketActor: SocketActor
- Vars:
  - DEBUG: "*"

[31m✘ [41;31m[[41;97mERROR[41;31m][0m [1mA request to the Cloudflare API (/accounts/xxxxxx/workers/scripts/sio-serverless-demo) failed.[0m

  Uncaught Error: Dynamic require of "url" is not supported
    at __require (main.js:13:9)
    at null.<anonymous> (file:///home/mikka/repos/socket.io-serverless/socket.io-serverless/dist/cf.js:15367:11)
   [code: 10021]

  
  If you think this is a bug, please open an issue at: [4mhttps://github.com/cloudflare/workers-sdk/issues/new/choose[0m


/home/mikka/repos/socket.io-serverless/demo-server:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @jokester/sio-serverless-demo-server@0.0.1 deploy:cf: `wrangler deploy`
Exit status 1

```

The error indicates that a dynamic require of the "url" module is not supported. It seems to be originating from the `cf.js` file within the `socket.io-serverless` package.

The CF.js is built using
```
	cd socket.io-serverless && node build.mjs
```

 Any ideas on how to debug or steps to resolve this problem would be greatly appreciated.

Thank you!

**Comment by jokester** [comment]
@cvyl Hi thanks for reaching out. 

This library is still in early development.

I more or less know how to fix this, but maybe not in this week. When it's ready for library users I will let you know.

**Comment by cvyl** [comment]
Thank you for your swift response! Appreciate your effort with this.

**Comment by jokester** [comment]
@cvyl the lib and demo server should build now.

I think I got the most basic features work. Please also check the latest readme for limitations.

I'm actually glad this work interested someone. Look forward to hear about your experience :pray:

**Comment by cvyl** [comment]
@jokester 

It is running fine locally with no real issues.
![{3A224859-FD48-484D-9FE8-C311906B7E3D}](https://github.com/user-attachments/assets/4a212cb0-343f-4632-9e19-0fbe059a1f69)
![{B0832981-2264-44F2-B730-02C53B06B6DB}](https://github.com/user-attachments/assets/6972a67f-677d-49b6-97b9-27f9944a3278)

Upon deploying on CF, I seem to run into the following error:
```
  (error) EngineActorBase#fetch() error creating EioSocket DataCloneError: Could not serialize an object of type "DurableObjectId". This type does not support serialization. 
GET https://playground.cvyl.me/socket.io/?EIO=4&transport=websocket - Unknown @ 12/10/2024, 21:24:03
```

I've been using both of your examples and edited them to send to a deployed version of your demo-server directory at `playground.cvyl.me` and I am unsure if I've done something wrong. The front end is not deployed. But can be edited from your domain `ihate.work` to mine. Overall I am thankful that you took time and effort into this project!

Edit: It's because my frontend isn't published it's not working. using a tester and manually sending data seems to work:
![{66A3D099-F5C6-4E2B-917B-E0F89BBBFA46}](https://github.com/user-attachments/assets/bddeebe1-4059-451d-a6c1-959e3cda64f9)
Could that be the problem?

**Comment by jokester** [comment]
The previous version did have a problem. DurableObjectId can be serialized in `wrangler dev` but not when deployed in CF. Should be fixed in latest `main`.

The `limb.jokester.io` server referenced in demo-client is a plain node.js socket.io server.

I think I have a working deployment in CF worker now. You can try again with recent code, or just use `https://sio-serverless-demo.ihate.work` for evaluation.

**Comment by cvyl** [comment]
Thank you for your swift response
I've tried the newest demo and it has deployed successfully. Pinging works.
https://sio-client.pages.dev

Turborepo source:
https://github.com/cvyl/socket-io-serverless-monorepo

My goal is to make a simple serverless real-time visitor count using this! If there's anything I can do to help you please let me know, I will mark this issue as solved now :)

**Comment by jokester** [comment]
I'm glad it worked for you. thanks for participating the alpha test 👍🏽
